name: 'SonarCloud Analysis'
author: 'Tiago Monteiro DECSKILL'
description: 'Cloud Pipeline'
inputs:
  LANGUAGE_VERSION:
    description: 'LANGUAGE_VERSION'
    required: true  
  SONAR_PROJECT_KEY:
    description: 'SonarCloud Project Key'
    required: true
  SONAR_ORGANIZATION:
    description: 'SonarCloud Organization'
    required: true
  SONAR_TOKEN:
    description: 'SonarCloud Token'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
        shell: bash

      - name: Build
        run: dotnet build --configuration Release

      - name: SonarCloud Analysis
        run: |
          dotnet-sonarscanner begin /k:"${{ inputs.SONAR_PROJECT_KEY }}" /o:"${{ inputs.SONAR_ORGANIZATION }}" /d:sonar.login="${{ inputs.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.coverage.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths=coverage.opencover.xml
          dotnet build --configuration Release
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet-sonarscanner end /d:sonar.login="${{ inputs.SONAR_TOKEN }}"

      - name: Check Quality Gate Status
        run: |
          echo "Checking SonarCloud Quality Gate Status..."
          status=$(curl -s -u "${{ inputs.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.SONAR_PROJECT_KEY }}&branch=main" | jq -r '.projectStatus.status')
          if [[ $status != "OK" ]]; then
            echo "Quality Gate check failed: $status"
            exit 1
          else
            echo "Quality Gate passed: $status"
          fi

      - name: Upload SonarCloud Analysis
        uses: actions/upload-artifact@main
        with:
          name: sonarcloud-artifact
          path: .
          retention-days: 1