name: SonarQube Analysis

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Adjust the Java version as needed

      - name: Build with Maven
        run: mvn clean install

      - name: Run SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          projectKey: your-project-key # Replace with your SonarQube project key
          projectName: Your Project Name # Replace with your project name
          serverUrl: https://http://localhost:8282/
          token: ${{ secrets.SONARQUBE_AUTH_TOKEN }}