name: CSHARP SONARQUBE
author: Tiago Monteiro
on:
  workflow_dispatch:
    inputs:
      LANGUAGE:
        required: true
        default: 'csharp'
        type: string
      LANGUAGE_VERSION:
        required: true
        default: 2.0
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: csharp
        if: ${{ inputs.LANGUAGE == 'csharp' }}
        uses: .github\actions\sonarqube-csharp\sonarqube-csharp.yml
        with:
          LANGUAGE_VERSION: ${{ inputs.LANGUAGE_VERSION }}