name: CSHARP SONARQUBE
on:
  workflow_dispatch:
    inputs:
      LANGUAGE:
        required: true
        default: 'csharp'
        type: string
      LANGUAGE_VERSION:
        required: true
        default: 2.0
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: csharp
        if: ${{ inputs.LANGUAGE == 'csharp' }}
        uses: dotnet-hello-world/.github/actions/sonarqube-csharp/action.yml@main
        with:
          LANGUAGE_VERSION: ${{ inputs.LANGUAGE_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v2